name: Actions 😎

on:
  pull_request: {}
  push: { branches: [master] }

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2019.4.1f1

jobs:
  testAndBuild:
    name: Tests on version ${{ matrix.unityVersion }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true
      
      # Cache
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library

      # Test
      - name: Run tests
        id: tests
        uses: webbertakken/unity-test-runner@v1.4
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          artifactsPath: tests-artifacts

      # Upload Test Artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: Test results
          path: ${{ steps.tests.outputs.artifactsPath }}

      # Build
      - uses: webbertakken/unity-builder@v1.0
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: StandaloneWindows

      # Upload Build Artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build
